### ISSUE TITLE
Ajouter une licence

### ISSUE THREAD

**Issue by bzg** [betagouv/monstage#93]
Bonjour ! [beta.gouv.fr](https://beta.gouv.fr/startups/monstage.html) indique que le code est « libre » mais je n'ai pas trouvé de licence sur le dépôt : je propose d'ajouter une licence MIT.

Qu'en dites-vous ?

**Comment by bzg** [comment]
Bonjour ! Est-ce que le projet est toujours actif ? Merci !

**Comment by mfo** [comment]
tjr en service ; c'est fait. 

PS: id d'amélioration continue ; PR direct, comme ca on a juste a merger

**Comment by bzg** [comment]
C'est noté !
